eventima/src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventsRepository::class)
 */
class Events
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $event_name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $event_descr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $event_img;

    /**
     * @ORM\Column(type="integer")
     */
    private $event_capac;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $cont_email;

    /**
     * @ORM\Column(type="integer")
     */
    private $cont_phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $event_address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $event_url;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $event_type;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEventName(): ?string
    {
        return $this->event_name;
    }

    public function setEventName(string $event_name): self
    {
        $this->event_name = $event_name;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->date_time;
    }

    public function setDateTime(\DateTimeInterface $date_time): self
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getEventDescr(): ?string
    {
        return $this->event_descr;
    }

    public function setEventDescr(string $event_descr): self
    {
        $this->event_descr = $event_descr;

        return $this;
    }

    public function getEventImg(): ?string
    {
        return $this->event_img;
    }

    public function setEventImg(?string $event_img): self
    {
        $this->event_img = $event_img;

        return $this;
    }

    public function getEventCapac(): ?int
    {
        return $this->event_capac;
    }

    public function setEventCapac(int $event_capac): self
    {
        $this->event_capac = $event_capac;

        return $this;
    }

    public function getContEmail(): ?string
    {
        return $this->cont_email;
    }

    public function setContEmail(string $cont_email): self
    {
        $this->cont_email = $cont_email;

        return $this;
    }

    public function getContPhone(): ?int
    {
        return $this->cont_phone;
    }

    public function setContPhone(int $cont_phone): self
    {
        $this->cont_phone = $cont_phone;

        return $this;
    }

    public function getEventAddress(): ?string
    {
        return $this->event_address;
    }

    public function setEventAddress(string $event_address): self
    {
        $this->event_address = $event_address;

        return $this;
    }

    public function getEventUrl(): ?string
    {
        return $this->event_url;
    }

    public function setEventUrl(string $event_url): self
    {
        $this->event_url = $event_url;

        return $this;
    }

    public function getEventType(): ?string
    {
        return $this->event_type;
    }

    public function setEventType(string $event_type): self
    {
        $this->event_type = $event_type;

        return $this;
    }
}

eventima/src/Controller/EventsController.php
<?php

namespace App\Controller;

//importing Form Components extentions
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

//importing the Events Entity
use App\Entity\Events;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;


class EventsController extends AbstractController
{
    public function index(): Response
    {
        // fetch all items from the class Events
        $events = $this->getDoctrine()->getRepository('App:Events')->findAll();
         //dd($events);
        return $this->render('events/index.html.twig', 
            array('eventsAll'=>$events)
        );
    }

    // function for adding event to DB
    public function create(Request $request): Response
    {   
        $events = new Events;
        // dd($events);
        $form = $this->createFormBuilder($events)
            ->add('event_name', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('event_descr', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('event_img', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('event_capac', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('cont_email', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('cont_phone', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('event_address', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))
            ->add('event_url', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        

            //date-time field
            ->add('date_time', DateTimeType::class, array('attr' => array('class'=>'','style'=>'margin-bottom:15px')))

            //event-type dropdown field
            ->add('event_type', ChoiceType::class, array('choices'=>array('exhibition'=>'exhibition', 'concert'=>'concert', 'cinema'=>'cinema', 'festival'=>'festival'),'attr' => array('class'=> 'form-control', 'style'=>'margin-botton:15px')))

            //submit button
            ->add('save', SubmitType::class, array('label'=> 'Create Event', 'attr' => array('class'=> 'btn mt-2 mb-2', 'style'=>'margin-bottom:15px')))

            ->getForm();

            $form->handleRequest($request);
        //dd($form);

        //if form submitted -- update DB
        if($form->isSubmitted() && $form->isValid()){
            //fetching data
            $event_name = $form['event_name']->getData();
            //dd($event_name);
            $event_descr = $form['event_descr']->getData();
            $event_img = $form['event_img']->getData();
            $event_capac = $form['event_capac']->getData();
            $cont_email = $form['cont_email']->getData();
            $cont_phone = $form['cont_phone']->getData();
            $event_address = $form['event_address']->getData();
            $event_url = $form['event_url']->getData();
            $date_time = $form['date_time']->getData();
            $event_type = $form['event_type']->getData();
            //dd($event_name);

            $events->setEventName($event_name);
            $events->setEventDescr($event_descr);
            $events->setEventImg($event_img);
            $events->setEventCapac($event_capac);
            $events->setContEmail($cont_email);
            $events->setContPhone($cont_phone);
            $events->setEventAddress($event_address);
            $events->setEventUrl($event_url);
            $events->setDateTime($date_time);
            $events->setEventType($event_type);

            //dd($events);

            $entityMngr = $this->getDoctrine()->getManager();
            
            //preparing data for upload to DB
            $entityMngr->persist($events);

            //query -- uploading data to DB
            $entityMngr->flush();

            //adding flash -- short msg to be display after submit
            $this->addFlash(
                'notice',
                'New Event Added'
            );
            return $this->redirectToRoute('index');
        }
        return $this->render('events/create.html.twig', 
            array('form'=>$form->createView())
        );
    }

    // function for editing event
    public function edit(Request $request, $id): Response
    {
        $events = $this->getDoctrine()->getRepository('App:Events')->find($id);

        $events->setEventName($events->getEventName());
        $events->setEventDescr($events->getEventDescr());
        $events->setEventImg($events->getEventImg());
        $events->setEventCapac($events->getEventCapac());
        $events->setContEmail($events->getContEmail());
        $events->setContPhone($events->getContPhone());
        $events->setEventAddress($events->getEventAddress());
        $events->setEventUrl($events->getEventUrl());
        $events->setEventType($events->getEventType());
        $events->setDateTime($events->getDateTime());
        //dd($events);

        $form = $this->createFormBuilder($events)
            ->add('event_name', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-botton:15px')))
            ->add('event_descr', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('event_img', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('event_capac', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('cont_email', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('cont_phone', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        
            ->add('event_address', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))
            ->add('event_url', TextType::class, array('attr' => array('class'=> 'form-control', 'style'=>'margin-bottom:15px')))        

            //date-time field
            ->add('date_time', DateTimeType::class, array('attr' => array('style'=>'margin-bottom:15px')))

            //event-type dropdown field
            ->add('event_type', ChoiceType::class, array('choices'=>array('exhibition'=>'exhibition', 'concert'=>'concert', 'cinema'=>'cinema', 'festival'=>'festival'),'attr' => array('class'=> 'form-control', 'style'=>'margin-botton:15px')))

            //submit button
            ->add('save', SubmitType::class, array('label'=> 'Save Changes', 'attr' => array('class'=> 'btn mt-2 mb-2', 'style'=>'margin-bottom:15px')))
            ->getForm();
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            //fetching data
            $event_name = $form['event_name']->getData();
            //dd($event_name);
            $event_descr = $form['event_descr']->getData();
            $event_img = $form['event_img']->getData();
            $event_capac = $form['event_capac']->getData();
            $cont_email = $form['cont_email']->getData();
            $cont_phone = $form['cont_phone']->getData();
            $event_address = $form['event_address']->getData();
            $event_url = $form['event_url']->getData();
            $date_time = $form['date_time']->getData();
            $event_type = $form['event_type']->getData();
            //dd($event_name);

            $entityMngr = $this->getDoctrine()->getManager();
            
            //preparing data for upload to DB
            $entityMngr->persist($events);

            //query -- uploading data to DB
            $entityMngr->flush();

            //adding flash -- short msg to be display after submit
            $this->addFlash(
                'notice',
                'Event has been updated'
            );
            return $this->redirectToRoute('index');
        }


        return $this->render('events/edit.html.twig',
            array('events' => $events, 'form' => $form->createView())
        );
    }

    // function for deleting events from DB
    public function delete($id): Response
    {
        $entityMngr = $this->getDoctrine()->getManager();
        $events = $entityMngr->getRepository('App:Events')->find($id);
        //dd($events);
        
        //removing the row & preparing it for update of DB
        $entityMngr->remove($events);

        //query --> updating the DB
        $entityMngr->flush();
        $this->addFlash(
            'notice',
            'Event has been deleted'
        );

        return $this->redirectToRoute('index');

        return $this->render('events/delete.html.twig',
            array('events' => $events, 'form' => $form->createView())
        );
    }

    // function for displayind a details page for each event
    public function details($id): Response
    {
        $events = $this->getDoctrine()->getRepository('App:Events')->find($id);
        //dd($events);
        return $this->render('events/details.html.twig', 
            array('events'=>$events)
        );
    }

    public function indexFilt(Request $request, string $event_type): Response {

eventima/templates/events/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add New Event{% endblock %}

{% block body %}
{{include('components/navbar.html.twig')}}

<div class="container mt-3 mb-3">
<h2 class="page-header">Add Event</h2>
    {{form_start(form)}}
    {{form_widget(form)}}
    {{form_end(form)}}</div>
{% endblock %}

eventima/templates/events/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EventsController!{% endblock %}

{% block body %}
{{include('components/navbar.html.twig')}}
<div class="container">
    if you see this, delete works
    <h2 class="page-header">Delete Event {{events.eventName}}</h2>
    <img src="{{events.eventImg}}" class="img-thumbnail" alt="{{events.eventName}}">

</div>
{% endblock %}

eventima/templates/events/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EventsController!{% endblock %}

{% block body %}
{{include('components/navbar.html.twig')}}

<div class="container mt-3 mb-3">
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{events.eventImg}}" class="detImg" alt="{{events.eventName}}">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{events.eventName}}</h5>
                    <p class="card-text">{{events.eventDescr}}</p>
                    <p class="card-text"><small class="text-muted">Date: {{events.dateTime | date('d/m/Y')}}</small></p>
                    <p class="card-text"><small class="text-muted">Time: {{events.dateTime | date('H:i')}}</small></p>
                    <p class="card-text"><small class="text-muted">Address: {{events.eventAddress}}</small></p>
                    <a class="card-text" href="{{events.contEmail}}"><small class="text-muted">Email: {{events.contEmail}}</small></a>
                    <p class="card-text"><small class="text-muted">Phone: {{events.contPhone}}</small></p>
                    <a class="link-dark" href="{{events.eventUrl}}"><small class="text-muted">Official Website: {{events.eventUrl}}</small></a> 

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

eventima/templates/events/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event {{events.eventName}}{% endblock %}

{% block body %}
{{include('components/navbar.html.twig')}}
<div class="container mt-3 mb-3">
    <h2 class="page-header">Edit Event: {{events.eventName}}</h2>
    <img src="{{events.eventImg}}" class="img-thumbnail" alt="{{events.eventName}}">
    {{form_start(form)}}

    {{form_widget(form)}}

    {{form_end(form)}}
</div>
{% endblock %}

eventima/templates/events/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome to Eventima{% endblock %}

{% block body %}

{{include('components/hero.html.twig')}}
<section id="events">
    <div class="container mt-3 mb-3">
        <h2 id="#events" class="text-center">Our Events</h2>
        <div class="btn-group mt-2 mb-2" role="group">
            <button id="btnGroupDrop1" type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Choose Event Type
            </button>
            <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <li><a class="dropdown-item" href="/">All</a></li>
                <li><a class="dropdown-item" href="/exhibition">Exhibition</a></li>
                <li><a class="dropdown-item" href="/concert">Concert</a></li>
                <li><a class="dropdown-item" href="/cinema">Cinema</a></li>
                <li><a class="dropdown-item" href="/festival">Festival</a></li>
            </ul>
        </div>
        
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4" id="#events">
            {% for event in eventsAll %}
            <div class="col">
                <div class="card cardZoom h-100">
                <img src="{{event.eventImg}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ event.eventName }}</h5>
                        <p class="card-text border-bottom">{{event.eventDescr}}</p>
                        <div class="mt-2 mb-2">
                            <p class="card-text m-0"><small class="text-muted">Date: {{event.dateTime | date('d/m/Y ')}}</small></p>
                            <p class="card-text m-0"> <small class="text-muted">Time: {{event.dateTime | date('H:i')}} </small></p>
                        </div>
                        
                        <div class="btn-group btn-group-sm">
                            <a href="/details/{{event.id}}" class="btn btn-outline-light">Details</a>
                            <a href="/edit/{{event.id}}" class="btn btn-outline-light">Edit</a>
                            <a href="/delete/{{event.id}}" class="btn btn-outline-light">Delete</a>
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}